const ShopActionTypes = {
   UPDATE_COLLECTIIONS: 'UPDATE_COLLECTIIONS',
   FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
   FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
   FETCH_COLLECTIONS_FAILURE : 'FETCH_COLLECTIONS_FAILURE'
};

export default ShopActionTypes;